<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="lk.pahana.edu.pahana_edu_billing_system.business.customer.dto.CustomerDTO" %>

<%
    CustomerDTO customer = (CustomerDTO) request.getAttribute("customer");
%>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Welcome to Pahana Edu</title>
</head>
<body style="font-family: Arial, sans-serif; background-color:#f5f5f5; margin:0; padding:20px;">

<div style="max-width:600px; margin:auto; background:#ffffff; border-radius:6px; overflow:hidden;">

    <!-- Header -->
    <div style="background:#222; color:#fff; padding:20px;">
        <h1 style="margin:0; font-size:22px;">Pahana Edu (Pvt) Ltd</h1>
        <p style="margin:4px 0 0; font-size:13px;">123 Main Street, Colombo, Sri Lanka | info@pahanaedu.com</p>
    </div>

    <!-- Welcome Message -->
    <div style="padding:20px; font-size:14px; color:#333;">
        <h2 style="margin-top:0; color:#333;">Welcome, <%= customer.getName() %>!</h2>
        <p>Thank you for joining Pahana Edu. We are thrilled to have you on board and look forward to helping you achieve your goals.</p>
        <p>You will now receive fully detailed bills to your registered email: <strong><%= customer.getEmail() %></strong>.</p>
        <p>If you have any questions or need assistance, feel free to contact us at <a href="mailto:info@pahanaedu.com">info@pahanaedu.com</a>.</p>
    </div>

    <!-- Footer -->
    <div style="padding:15px 20px; border-top:1px solid #ddd; font-size:12px; text-align:center; color:#777;">
        <p style="margin:2px 0;">Welcome to the Pahana Edu family!</p>
        <p style="margin:2px 0;">Email generated by Pahana Edu System</p>
    </div>

</div>

</body>
</html>
