<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="lk.pahana.edu.pahana_edu_billing_system.business.bill.dto.InvoiceDTO" %>
<%@ page import="lk.pahana.edu.pahana_edu_billing_system.business.customer.dto.CustomerDTO" %>
<%@ page import="lk.pahana.edu.pahana_edu_billing_system.business.bill.dto.InvoiceItemDTO" %>

<%
    InvoiceDTO bill = (InvoiceDTO) request.getAttribute("bill");
    CustomerDTO customer = (CustomerDTO) request.getAttribute("customer");
%>

<html lang="en" data-theme="night">
<%@ include file="../partials/header.jsp" %>
<head>
    <style>
        @media print {
            #printButton {
                display: none;
            }

            #backButton {
                display: none;
            }

            #sendButton {
                display: none;
            }
        }
    </style>
</head>
<body class="p-6">

<div class="flex justify-between px-8 py-4">
    <div>
        <a id="backButton" href="<%= request.getContextPath() %>/bill" class="btn btn-neutral">
            <i class="fa-solid fa-arrow-left"></i>Back
        </a>
    </div>
    <div>
        <button id="printButton" onclick="window.print()" class="btn btn-primary mr-2">
            <i class="fa-solid fa-print"></i> Print Invoice
        </button>
        <form action="<%= request.getContextPath() %>/bill/sendEmail" method="post" style="display:inline;">
            <input type="hidden" name="billId" value="<%= bill.getBillId() %>">
            <input type="hidden" name="customerEmail" value="<%= customer.getEmail() %>">
            <button id="sendButton" type="submit" class="btn btn-accent">
                <i class="fa-solid fa-envelope"></i> Send Email
            </button>
        </form>
    </div>
</div>

<div class="max-w-3xl mx-auto bg-gray-100 text-gray-800 font-sans rounded-lg overflow-hidden">

    <div class="bg-gray-900 text-gray-100 px-6 py-6">
        <div class="flex items-center justify-between">
            <div>
                <h1 class="text-3xl font-bold">Pahana Edu (Pvt) Ltd</h1>
                <p class="text-sm opacity-75">123 Main Street, Colombo, Sri Lanka | info@pahanaedu.com</p>
            </div>
            <i class="fa-solid fa-book-open text-3xl"></i>
        </div>
    </div>

    <div class="px-6 py-4 border-b border-gray-300 flex items-center gap-2">
        <i class="fa-solid fa-file-invoice text-2xl text-gray-600"></i>
        <h2 class="text-2xl font-bold text-gray-600">Invoice</h2>
    </div>

    <div class="px-6 py-4 space-y-1 text-sm">
        <p><strong>Invoice ID:</strong> <%= bill.getBillId() %>
        </p>
        <p><strong>Date:</strong> <%= new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) %>
        </p>
        <p><strong>Customer:</strong> <%= customer.getName() %>
        </p>
        <p><strong>Mobile:</strong> <%= customer.getMobileNumber() %>
    </div>

    <!-- Items Table -->
    <div class="p-6">
        <table class="w-full text-sm border-collapse">
            <thead>
            <tr class="bg-gray-300 text-gray-800 font-semibold">
                <th class="py-2 px-3 text-left">Item</th>
                <th class="py-2 px-3 text-right">Qty</th>
                <th class="py-2 px-3 text-right">Unit Price</th>
                <th class="py-2 px-3 text-right">Total</th>
            </tr>
            </thead>
            <tbody>
            <% for (InvoiceItemDTO item : bill.getBillItems()) { %>
            <tr class="border-t border-gray-300 text-gray-700">
                <td class="py-2 px-3 font-medium"><%= item.getItemName() %></td>
                <td class="py-2 px-3 text-right"><%= item.getQuantity() %></td>
                <td class="py-2 px-3 text-right">Rs. <%= item.getUnitPrice() %></td>
                <td class="py-2 px-3 text-right font-semibold">Rs. <%= item.getUnitPrice() * item.getQuantity() %></td>
            </tr>
            <% } %>
            </tbody>
        </table>
    </div>

    <!-- Total -->
    <div class="px-6 py-4 border-t border-gray-300 text-right">
        <p class="text-xl font-bold">Total: Rs. <%= bill.getTotalAmount() %>
        </p>
    </div>

    <!-- Footer -->
    <div class="px-6 py-4 text-center text-xs text-gray-600 border-t border-gray-300">
        <p>Thank you for your business</p>
        <p>Invoice generated by Pahana Edu Billing System</p>
    </div>
</div>

</body>
</html>
