<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="lk.pahana.edu.pahana_edu_billing_system.business.bill.dto.InvoiceDTO" %>
<%@ page import="lk.pahana.edu.pahana_edu_billing_system.business.customer.dto.CustomerDTO" %>
<%@ page import="lk.pahana.edu.pahana_edu_billing_system.business.bill.dto.InvoiceItemDTO" %>

<%
    InvoiceDTO bill = (InvoiceDTO) request.getAttribute("bill");
    CustomerDTO customer = (CustomerDTO) request.getAttribute("customer");
%>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
</head>
<body style="font-family: Arial, sans-serif; background-color:#f5f5f5; margin:0; padding:20px;">

<div style="max-width:600px; margin:auto; background:#ffffff; border-radius:6px; overflow:hidden;">

    <!-- Header -->
    <div style="background:#222; color:#fff; padding:20px;">
        <h1 style="margin:0; font-size:22px;">Pahana Edu (Pvt) Ltd</h1>
        <p style="margin:4px 0 0; font-size:13px;">123 Main Street, Colombo, Sri Lanka | info@pahanaedu.com</p>
    </div>

    <!-- Invoice title -->
    <div style="padding:15px 20px; border-bottom:1px solid #ddd;">
        <h2 style="margin:0; font-size:20px; color:#333;">Invoice</h2>
    </div>

    <!-- Customer Info -->
    <div style="padding:20px; font-size:14px; color:#333;">
        <p><strong>Invoice ID:</strong> <%= bill.getBillId() %></p>
        <p><strong>Date:</strong> <%= new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) %></p>
        <p><strong>Customer:</strong> <%= customer.getName() %></p>
        <p><strong>Mobile:</strong> <%= customer.getMobileNumber() %></p>
    </div>

    <!-- Items Table -->
    <div style="padding:0 20px 20px;">
        <table width="100%" border="0" cellspacing="0" cellpadding="8" style="border-collapse:collapse; font-size:14px;">
            <thead>
            <tr style="background:#eee; text-align:left;">
                <th style="border:1px solid #ddd;">Item</th>
                <th style="border:1px solid #ddd; text-align:right;">Qty</th>
                <th style="border:1px solid #ddd; text-align:right;">Unit Price</th>
                <th style="border:1px solid #ddd; text-align:right;">Total</th>
            </tr>
            </thead>
            <tbody>
            <% for (InvoiceItemDTO item : bill.getBillItems()) { %>
            <tr>
                <td style="border:1px solid #ddd;"><%= item.getItemName() %></td>
                <td style="border:1px solid #ddd; text-align:right;"><%= item.getQuantity() %></td>
                <td style="border:1px solid #ddd; text-align:right;">Rs. <%= item.getUnitPrice() %></td>
                <td style="border:1px solid #ddd; text-align:right;">Rs. <%= item.getUnitPrice() * item.getQuantity() %></td>
            </tr>
            <% } %>
            </tbody>
        </table>
    </div>

    <!-- Total -->
    <div style="padding:15px 20px; border-top:1px solid #ddd; text-align:right;">
        <p style="font-size:16px; font-weight:bold; margin:0;">Total: Rs. <%= bill.getTotalAmount() %></p>
    </div>

    <!-- Footer -->
    <div style="padding:15px 20px; border-top:1px solid #ddd; font-size:12px; text-align:center; color:#777;">
        <p style="margin:2px 0;">Thank you for your business</p>
        <p style="margin:2px 0;">Invoice generated by Pahana Edu Billing System</p>
    </div>
</div>

</body>
</html>
